language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hardgrdb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hardgrdb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "DockerReact2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-434478805792"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY